apiVersion: v1
kind: Service
metadata:
  name: genre-service-postgres
  labels:
    app: genre-service
spec:
  ports:
    - port: 5432
  selector:
    app: genre-service
    tier: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genre-service-postgres-deployment
  labels:
    app: genre-service
spec:
  selector:
    matchLabels:
      app: genre-service
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: genre-service
        tier: postgres
    spec:
      containers:
        - image: postgres
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: genre
            - name: POSTGRES_USER
              value: genre
            - name: POSTGRES_PASSWORD
              value: genre123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genre-service-server-deployment
  labels:
    app: genre-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genre-service-server
  template:
    metadata:
      labels:
        app: genre-service-server
    spec:
      containers:
        - name: genre-service-server
          image: jonaulaerts/genre-service
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8054
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:
            - name: POSTGRES_DB_HOST
              value: "genre-service-postgres"
            - name: POSTGRES_DB_PORT
              value: "5432"
            - name: POSTGRES_DB_USERNAME
              value: "genre"
            - name: POSTGRES_DB_PASSWORD
              value: ${GENRE_POSTGRES_PASSWORD:genre1234}
---
apiVersion: v1
kind: Service
metadata:
  name: genre-service-server
  labels:
    app: genre-service-server
spec:
  type: NodePort
  selector:
    app: genre-service-server
  ports:
    - name: http
      port: 8054
      targetPort: 8054